#define DEBOUNCE 15
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define DYNAMIC_KEYMAP_MACRO_COUNT 60
#define BACKLIGHT_PIN A8
#define BACKLIGHT_GPT_DRIVER GPTD1
#define BACKLIGHT_LEVELS 20
#define BACKLIGHT_DEFAULT_LEVEL 3
#define BACKLIGHT_ON_STATE 1
#define BACKLIGHT_LEVEL_STORAGE
#define BOOTMAGIC_ROW 2
#define BOOTMAGIC_COLUMN 0